import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  const { refreshToken, error, errorDescription } = router.query;
  return (
    <>
      <Head>
        <title>Chaldean Numbers Webviews</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {refreshToken && (
          <>
            <div className={styles.text}>
              Your email has been verified. You can close this page and login to
              the application.
            </div>
            <div className={styles.closeContainer}>
              <div
                className={styles.closingCross}
                onClick={() => {
                  window.open('', '_self');
                  window.close();
                }}
              >
                X
              </div>
            </div>
          </>
        )}

        {errorDescription && (
          <>
            <div className={styles.text}>{errorDescription}</div>
            <div className={styles.text}>
              Please ask for a new email verification through the application.
            </div>
            <div className={styles.closeContainer}>
              <div
                className={styles.closingCross}
                onClick={() => {
                  window.open('', '_self');
                  window.close();
                }}
              >
                X
              </div>
            </div>
          </>
        )}
      </main>
    </>
  );
}
